services:
  minio:
    image: minio/minio
    entrypoint: sh
    command: >
      -c 'mkdir -p /data/test-bucket && minio server /data'
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
      - MINIO_ADDRESS
      - MINIO_CONSOLE_ADDRESS
    volumes:
      - minio_data:/data

volumes:
  minio_data:
