services:
  nginx:
    image: nginx:alpine
    container_name: nginx-init
    ports:
      - "80:80"
    volumes:
      - ./nginx/init_sert/nginx.conf:/etc/nginx/nginx.conf:ro
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - shelter_network

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email gnonasis@gmail.com --agree-tos --no-eff-email --staging -d sha-man.pp.ua
    networks:
      - shelter_network

volumes:
  etc-letsencrypt:
  www-html:

networks:
  shelter_network:
    driver: bridge
