import { Pet } from '../types/Pet';
// import api from './api';
const tempData = JSON.stringify([
  {
    id: 1,
    name: 'Buddy',
    pet_type: 'Dog',
    age: 3.2,
    breed: 'Golden Retriever',
    sex: 'Male',
    coloration: 'Golden',
    weight: 70,
    is_sterilized: true,
    description:
      "Buddy is a friendly and energetic companion who loves to play fetch and go for long walks. He's great with kids and other dogs.",
    date_created: '2024-05-15T10:30:00.000Z',
    picture: 'https://placehold.co/100x900/EEE/31343C?text=Buddyy',
  },
  {
    id: 2,
    name: 'Luna',
    pet_type: 'Cat',
    age: 1.5,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Black',
    weight: 10,
    is_sterilized: true,
    description:
      'Luna is a sleek and curious cat with a playful spirit. She loves chasing laser pointers and cuddling up for a nap in a sunny spot.',
    date_created: '2024-08-22T14:00:00.000Z',
    picture: 'https://placehold.co/600x7400/EEE/31343C?text=Luna',
  },
  {
    id: 3,
    name: 'Charlie',
    pet_type: 'Dog',
    age: 5,
    breed: 'Beagle',
    sex: 'Male',
    coloration: 'Tricolor',
    weight: 25,
    is_sterilized: true,
    description:
      'Charlie is a sweet-natured beagle with a nose for adventure. He enjoys sniffing around the yard and is very treat-motivated.',
    date_created: '2023-11-10T11:20:00.000Z',
    picture: 'https://placehold.co/200x600/EEE/31343C?text=Charlie',
  },
  {
    id: 4,
    name: 'Bella',
    pet_type: 'Dog',
    age: 0.8,
    breed: 'Poodle',
    sex: 'Female',
    coloration: 'White',
    weight: 15,
    is_sterilized: false,
    description:
      "Bella is an intelligent and playful poodle puppy. She's learning commands quickly and loves to be the center of attention.",
    date_created: '2025-02-01T16:45:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Bella',
  },
  {
    id: 5,
    name: 'Oliver',
    pet_type: 'Cat',
    age: 2.1,
    breed: 'Siamese',
    sex: 'Male',
    coloration: 'Cream Point',
    weight: 12,
    is_sterilized: true,
    description:
      "Oliver is a vocal and affectionate Siamese who loves to 'talk'. He is very social and enjoys being around people.",
    date_created: '2024-09-05T09:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Oliver',
  },
  {
    id: 6,
    name: 'Max',
    pet_type: 'Dog',
    age: 6.7,
    breed: 'German Shepherd',
    sex: 'Male',
    coloration: 'Black and Tan',
    weight: 85,
    is_sterilized: true,
    description:
      'Max is a loyal and protective German Shepherd. He is well-trained and would thrive in a home with a strong leader.',
    date_created: '2023-07-20T18:10:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Max',
  },
  {
    id: 7,
    name: 'Lucy',
    pet_type: 'Dog',
    age: 2.5,
    breed: 'Labrador Retriever',
    sex: 'Female',
    coloration: 'Chocolate',
    weight: 65,
    is_sterilized: true,
    description:
      'Lucy is a happy-go-lucky Labrador who has never met a stranger. Her tail is always wagging and she loves swimming.',
    date_created: '2024-12-18T13:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Lucy',
  },
  {
    id: 8,
    name: 'Milo',
    pet_type: 'Cat',
    age: 4,
    breed: 'Maine Coon',
    sex: 'Male',
    coloration: 'Brown Tabby',
    weight: 18,
    is_sterilized: true,
    description:
      'Milo is a gentle giant with a magnificent coat. He is calm, and good-natured, and gets along well with other pets.',
    date_created: '2024-02-14T12:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Milo',
  },
  {
    id: 9,
    name: 'Daisy',
    pet_type: 'Dog',
    age: 0.8,
    breed: 'Mixed Breed',
    sex: 'Female',
    coloration: 'Brown and White',
    weight: 30,
    is_sterilized: false,
    description:
      'Daisy is a delightful mixed-breed puppy full of curiosity and joy. She is looking for a family to grow up with.',
    date_created: '2025-01-25T11:50:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Daisy',
  },
  {
    id: 10,
    name: 'Simba',
    pet_type: 'Cat',
    age: 3.8,
    breed: 'Domestic Longhair',
    sex: 'Male',
    coloration: 'Orange Tabby',
    weight: 14,
    is_sterilized: true,
    description:
      'Simba is a confident and regal cat who loves to survey his kingdom from a high perch. He enjoys gentle pets and a quiet home.',
    date_created: '2024-06-30T15:20:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Simba',
  },
  {
    id: 11,
    name: 'Rocky',
    pet_type: 'Dog',
    age: 4.3,
    breed: 'Boxer',
    sex: 'Male',
    coloration: 'Brindle',
    weight: 68,
    is_sterilized: true,
    description:
      'Rocky is a goofy and playful Boxer with endless energy. He would be a perfect running or hiking partner.',
    date_created: '2024-03-03T17:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Rocky',
  },
  {
    id: 12,
    name: 'Chloe',
    pet_type: 'Cat',
    age: 6,
    breed: 'Ragdoll',
    sex: 'Female',
    coloration: 'Seal Point',
    weight: 13,
    is_sterilized: true,
    description:
      'Chloe is a classic Ragdoll who goes limp in your arms. She is incredibly docile and loves a calm, peaceful environment.',
    date_created: '2023-09-12T10:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Chloe',
  },
  {
    id: 13,
    name: 'Zoe',
    pet_type: 'Dog',
    age: 1.1,
    breed: 'French Bulldog',
    sex: 'Female',
    coloration: 'Fawn',
    weight: 22,
    is_sterilized: true,
    description:
      'Zoe is a comical and charming French Bulldog. She loves to snuggle and make her people laugh with her silly antics.',
    date_created: '2025-01-02T12:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Zoe',
  },
  {
    id: 14,
    name: 'Jasper',
    pet_type: 'Cat',
    age: 0.9,
    breed: 'Domestic Shorthair',
    sex: 'Male',
    coloration: 'Gray Tuxedo',
    weight: 9,
    is_sterilized: false,
    description:
      'Jasper is a dapper young cat who is always dressed to impress in his tuxedo coat. He is adventurous and loves to explore.',
    date_created: '2025-03-11T14:45:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Jasper',
  },
  {
    id: 15,
    name: 'Ruby',
    pet_type: 'Dog',
    age: 7,
    breed: 'Cavalier King Charles Spaniel',
    sex: 'Female',
    coloration: 'Blenheim',
    weight: 18,
    is_sterilized: true,
    description:
      'Ruby is an absolute sweetheart who wants nothing more than a warm lap to curl up in. She is gentle and affectionate.',
    date_created: '2023-05-21T11:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Ruby',
  },
  {
    id: 16,
    name: 'Winston',
    pet_type: 'Dog',
    age: 5,
    breed: 'English Bulldog',
    sex: 'Male',
    coloration: 'White and Fawn',
    weight: 50,
    is_sterilized: true,
    description:
      'Winston is a lovable couch potato with a heart of gold. He enjoys short strolls and long naps.',
    date_created: '2024-01-10T16:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Winston',
  },
  {
    id: 17,
    name: 'Nala',
    pet_type: 'Cat',
    age: 2.8,
    breed: 'Bengal',
    sex: 'Female',
    coloration: 'Spotted/Rosetted',
    weight: 11,
    is_sterilized: true,
    description:
      'Nala is an active and intelligent Bengal with stunning markings. She needs a stimulating environment with plenty of toys.',
    date_created: '2024-11-08T18:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Nala',
  },
  {
    id: 18,
    name: 'Toby',
    pet_type: 'Dog',
    age: 8,
    breed: 'Shetland Sheepdog',
    sex: 'Male',
    coloration: 'Sable and White',
    weight: 20,
    is_sterilized: true,
    description:
      'Toby is a smart and sensitive Sheltie who is very devoted to his family. He is a little shy at first but warms up quickly.',
    date_created: '2023-04-19T09:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Toby',
  },
  {
    id: 19,
    name: 'Penny',
    pet_type: 'Dog',
    age: 0.5,
    breed: 'Dachshund',
    sex: 'Female',
    coloration: 'Red',
    weight: 10,
    is_sterilized: false,
    description:
      'Penny is a spunky and curious Dachshund puppy. She is brave and loves to burrow in blankets.',
    date_created: '2025-04-01T10:15:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Penny',
  },
  {
    id: 20,
    name: 'Smokey',
    pet_type: 'Cat',
    age: 10,
    breed: 'Domestic Shorthair',
    sex: 'Male',
    coloration: 'Gray',
    weight: 12,
    is_sterilized: true,
    description:
      'Smokey is a distinguished senior cat looking for a quiet retirement home. He is a world-class napper and a gentle soul.',
    date_created: '2024-07-14T11:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Smokey',
  },
  {
    id: 21,
    name: 'Sadie',
    pet_type: 'Dog',
    age: 3,
    breed: 'Australian Shepherd',
    sex: 'Female',
    coloration: 'Blue Merle',
    weight: 45,
    is_sterilized: true,
    description:
      'Sadie is a highly intelligent and energetic Aussie. She would excel at agility training or as a companion for an active owner.',
    date_created: '2024-10-25T13:20:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Sadie',
  },
  {
    id: 22,
    name: 'Gus',
    pet_type: 'Dog',
    age: 6,
    breed: 'Basset Hound',
    sex: 'Male',
    coloration: 'Tricolor',
    weight: 55,
    is_sterilized: true,
    description:
      'Gus is a laid-back Basset Hound who loves two things: food and naps. He is incredibly charming and easygoing.',
    date_created: '2023-12-01T14:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Gus',
  },
  {
    id: 23,
    name: 'Misty',
    pet_type: 'Cat',
    age: 1.2,
    breed: 'Russian Blue',
    sex: 'Female',
    coloration: 'Silver-Blue',
    weight: 9,
    is_sterilized: true,
    description:
      'Misty is a graceful and gentle cat with a shimmering coat. She can be reserved with new people but is very loving once she knows you.',
    date_created: '2025-01-05T18:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Misty',
  },
  {
    id: 24,
    name: 'Duke',
    pet_type: 'Dog',
    age: 7,
    breed: 'Great Dane',
    sex: 'Male',
    coloration: 'Fawn',
    weight: 150,
    is_sterilized: true,
    description:
      "Duke is a true gentle giant. Despite his size, he thinks he's a lap dog and is incredibly sweet with everyone he meets.",
    date_created: '2023-08-15T15:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Duke',
  },
  {
    id: 25,
    name: 'Willow',
    pet_type: 'Cat',
    age: 2.5,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Calico',
    weight: 8,
    is_sterilized: true,
    description:
      "Willow has beautiful calico markings and a personality to match. She's independent but enjoys a good head scratch.",
    date_created: '2024-11-20T19:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Willow',
  },
  {
    id: 26,
    name: 'Bear',
    pet_type: 'Dog',
    age: 5,
    breed: 'Newfoundland',
    sex: 'Male',
    coloration: 'Black',
    weight: 140,
    is_sterilized: true,
    description:
      'Bear is a big, fluffy teddy bear of a dog. He is calm, patient, and adores children. Great for a family with a large yard.',
    date_created: '2024-04-10T12:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Bear',
  },
  {
    id: 27,
    name: 'Cleo',
    pet_type: 'Cat',
    age: 4,
    breed: 'Sphynx',
    sex: 'Female',
    coloration: 'Pink',
    weight: 10,
    is_sterilized: true,
    description:
      "Cleo is a hairless wonder who loves to be warm and cozy. She's a little heat-seeking missile who will snuggle under any blanket.",
    date_created: '2024-08-01T11:45:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Cleo',
  },
  {
    id: 28,
    name: 'Finn',
    pet_type: 'Dog',
    age: 1.5,
    breed: 'Irish Setter',
    sex: 'Male',
    coloration: 'Mahogany',
    weight: 60,
    is_sterilized: false,
    description:
      "Finn has a stunning red coat and a boundless enthusiasm for life. He's a very active dog looking for an equally active owner.",
    date_created: '2025-02-18T10:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Finn',
  },
  {
    id: 29,
    name: 'Hazel',
    pet_type: 'Cat',
    age: 0.7,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Tortoiseshell',
    weight: 7,
    is_sterilized: false,
    description:
      "Hazel is a kitten with a 'tortitude'! She is sassy, playful, and full of personality. Guaranteed to keep you entertained.",
    date_created: '2025-05-05T14:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Hazel',
  },
  {
    id: 30,
    name: 'Apollo',
    pet_type: 'Dog',
    age: 2,
    breed: 'Siberian Husky',
    sex: 'Male',
    coloration: 'Black and White',
    weight: 55,
    is_sterilized: true,
    description:
      "Apollo is a striking husky with piercing blue eyes. He loves to run and would be a great fit for a home that understands the breed's needs.",
    date_created: '2024-10-10T16:20:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Apollo',
  },
  {
    id: 31,
    name: 'Athena',
    pet_type: 'Dog',
    age: 2,
    breed: 'Siberian Husky',
    sex: 'Female',
    coloration: 'Gray and White',
    weight: 50,
    is_sterilized: true,
    description:
      "Athena is Apollo's sister, a beautiful husky who is a bit more reserved but just as loving. They would love to be adopted together!",
    date_created: '2024-10-10T16:20:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Athena',
  },
  {
    id: 32,
    name: 'Loki',
    pet_type: 'Cat',
    age: 3,
    breed: 'Bombay',
    sex: 'Male',
    coloration: 'Black',
    weight: 11,
    is_sterilized: true,
    description:
      'Loki is a mischievous but charming mini-panther. He is sleek, intelligent, and loves to get into playful trouble.',
    date_created: '2024-09-28T13:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Loki',
  },
  {
    id: 33,
    name: 'Stella',
    pet_type: 'Dog',
    age: 4,
    breed: 'Pit Bull Terrier',
    sex: 'Female',
    coloration: 'Blue',
    weight: 55,
    is_sterilized: true,
    description:
      "Stella is a total sweetheart who defies stereotypes. She's a big cuddle bug who loves people and wants to be your best friend.",
    date_created: '2024-06-15T09:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Stella',
  },
  {
    id: 34,
    name: 'Oscar',
    pet_type: 'Cat',
    age: 8,
    breed: 'British Shorthair',
    sex: 'Male',
    coloration: 'Blue-Gray',
    weight: 15,
    is_sterilized: true,
    description:
      'Oscar is a plush and dignified gentleman. He prefers a quiet life filled with sunbeams and soft beds. A true low-maintenance companion.',
    date_created: '2023-10-02T15:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Oscar',
  },
  {
    id: 35,
    name: 'Kona',
    pet_type: 'Dog',
    age: 3,
    breed: 'Rhodesian Ridgeback',
    sex: 'Female',
    coloration: 'Wheaten',
    weight: 75,
    is_sterilized: true,
    description:
      'Kona is an athletic and loyal dog. She is looking for an experienced owner who can continue her training and provide plenty of exercise.',
    date_created: '2024-08-30T17:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Kona',
  },
  {
    id: 36,
    name: 'Riley',
    pet_type: 'Dog',
    age: 0.6,
    breed: 'Golden Doodle',
    sex: 'Male',
    coloration: 'Cream',
    weight: 25,
    is_sterilized: false,
    description:
      'Riley is a fluffy and friendly puppy who is almost too cute to handle. He is very social and is looking for an active family.',
    date_created: '2025-04-12T11:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Riley',
  },
  {
    id: 37,
    name: 'Ziggy',
    pet_type: 'Cat',
    age: 2,
    breed: 'Domestic Shorthair',
    sex: 'Male',
    coloration: 'Brown Tabby w/ White',
    weight: 10,
    is_sterilized: true,
    description:
      "Ziggy is a fun-loving cat with a big personality. He's curious about everything and will follow you around the house to supervise.",
    date_created: '2025-01-20T10:45:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Ziggy',
  },
  {
    id: 38,
    name: 'Bailey',
    pet_type: 'Dog',
    age: 6,
    breed: 'Shih Tzu',
    sex: 'Female',
    coloration: 'White and Gold',
    weight: 14,
    is_sterilized: true,
    description:
      'Bailey is a pampered princess who loves to be brushed and doted on. She is a perfect lap dog for a loving home.',
    date_created: '2023-11-15T13:15:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Bailey',
  },
  {
    id: 39,
    name: 'Frankie',
    pet_type: 'Dog',
    age: 4,
    breed: 'Boston Terrier',
    sex: 'Male',
    coloration: 'Black and White',
    weight: 20,
    is_sterilized: true,
    description:
      "Frankie is a true gentleman in a tuxedo. He's playful, smart, and has a comical personality that will keep you smiling.",
    date_created: '2024-07-22T12:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Frankie',
  },
  {
    id: 40,
    name: 'Piper',
    pet_type: 'Cat',
    age: 1,
    breed: 'Scottish Fold',
    sex: 'Female',
    coloration: 'Gray',
    weight: 9,
    is_sterilized: true,
    description:
      'With her adorable folded ears, Piper is as cute as they come. She is sweet-tempered, gentle, and loves quiet afternoons.',
    date_created: '2025-03-01T16:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Piper',
  },
  {
    id: 41,
    name: 'Leo',
    pet_type: 'Cat',
    age: 5,
    breed: 'Domestic Longhair',
    sex: 'Male',
    coloration: 'Ginger',
    weight: 16,
    is_sterilized: true,
    description:
      'Leo is a magnificent, fluffy cat with a mane like a lion. He is confident, affectionate, and loves a good chin scratch.',
    date_created: '2024-02-20T14:20:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Leo',
  },
  {
    id: 42,
    name: 'Maddie',
    pet_type: 'Dog',
    age: 8,
    breed: 'Cocker Spaniel',
    sex: 'Female',
    coloration: 'Buff',
    weight: 28,
    is_sterilized: true,
    description:
      'Maddie is a sweet senior girl with soulful eyes. She is looking for a comfy couch and a family to give her gentle affection.',
    date_created: '2023-09-01T10:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Maddie',
  },
  {
    id: 43,
    name: 'Hank',
    pet_type: 'Dog',
    age: 9,
    breed: 'Bloodhound',
    sex: 'Male',
    coloration: 'Red',
    weight: 95,
    is_sterilized: true,
    description:
      "Hank is a classic droopy-eared hound. He's a gentle old soul who loves to follow scents and then take a very long nap.",
    date_created: '2023-06-10T11:10:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Hank',
  },
  {
    id: 44,
    name: 'Olive',
    pet_type: 'Cat',
    age: 2,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Gray Tabby',
    weight: 10,
    is_sterilized: true,
    description:
      "Olive is a petite and sweet-natured tabby. She's a bit shy at first but will purr up a storm once she feels safe and loved.",
    date_created: '2024-12-05T12:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Olive',
  },
  {
    id: 45,
    name: 'Moose',
    pet_type: 'Dog',
    age: 3,
    breed: 'Bernese Mountain Dog',
    sex: 'Male',
    coloration: 'Tricolor',
    weight: 110,
    is_sterilized: true,
    description:
      'Moose is a big, friendly goofball. He is good-natured, loves the outdoors (especially snow!), and is a fantastic family dog.',
    date_created: '2024-09-18T18:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Moose',
  },
  {
    id: 46,
    name: 'Ivy',
    pet_type: 'Cat',
    age: 0.5,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Black and White',
    weight: 5,
    is_sterilized: false,
    description:
      'Ivy is a tiny kitten with a huge personality. She is full of boundless energy, loves to pounce, and is learning about the world.',
    date_created: '2025-05-15T10:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Ivy',
  },
  {
    id: 47,
    name: 'Jax',
    pet_type: 'Dog',
    age: 1,
    breed: 'German Shorthaired Pointer',
    sex: 'Male',
    coloration: 'Liver and White',
    weight: 60,
    is_sterilized: false,
    description:
      'Jax is a high-energy dog built for action. He is incredibly smart and needs a job to do, like running, hiking, or fetching.',
    date_created: '2025-02-25T14:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Jax',
  },
  {
    id: 48,
    name: 'Rosie',
    pet_type: 'Dog',
    age: 10,
    breed: 'Pomeranian',
    sex: 'Female',
    coloration: 'Orange Sable',
    weight: 7,
    is_sterilized: true,
    description:
      'Rosie is a lovely senior lady who is still spunky and sweet. She enjoys short walks and being a cherished companion.',
    date_created: '2023-03-20T16:45:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Rosie',
  },
  {
    id: 49,
    name: 'Shadow',
    pet_type: 'Cat',
    age: 7,
    breed: 'Domestic Longhair',
    sex: 'Male',
    coloration: 'Black',
    weight: 13,
    is_sterilized: true,
    description:
      'Shadow is a mysterious and handsome cat who likes to observe from a distance before coming in for cuddles on his own terms.',
    date_created: '2023-10-31T19:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Shadow',
  },
  {
    id: 50,
    name: 'Scout',
    pet_type: 'Dog',
    age: 2,
    breed: 'Border Collie',
    sex: 'Male',
    coloration: 'Black and White',
    weight: 40,
    is_sterilized: true,
    description:
      'Scout is wicked smart and needs to keep his brain busy. He lives for learning new tricks and playing with puzzle toys.',
    date_created: '2024-11-11T11:11:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Scout',
  },
  {
    id: 51,
    name: 'Cookie',
    pet_type: 'Dog',
    age: 5,
    breed: 'Chihuahua',
    sex: 'Female',
    coloration: 'Fawn',
    weight: 6,
    is_sterilized: true,
    description:
      'Cookie is a tiny dog with a huge, loving heart. She can be a bit shy but is a loyal and devoted friend once she trusts you.',
    date_created: '2024-05-05T13:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Cookie',
  },
  {
    id: 52,
    name: 'Patches',
    pet_type: 'Cat',
    age: 6,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'White with Gray Patches',
    weight: 11,
    is_sterilized: true,
    description:
      'Patches is a sweet girl with a calm demeanor. She is an expert at finding the most comfortable spot in the house for a nap.',
    date_created: '2024-01-28T10:10:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Patches',
  },
  {
    id: 53,
    name: 'Chester',
    pet_type: 'Cat',
    age: 3,
    breed: 'American Shorthair',
    sex: 'Male',
    coloration: 'Orange Tabby',
    weight: 13,
    is_sterilized: true,
    description:
      "Chester is a classic, friendly orange tabby. He's easygoing, loves attention, and gets along well with just about everyone.",
    date_created: '2024-08-08T08:08:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Chester',
  },
  {
    id: 54,
    name: 'Abby',
    pet_type: 'Dog',
    age: 7,
    breed: 'Vizsla',
    sex: 'Female',
    coloration: 'Golden Rust',
    weight: 50,
    is_sterilized: true,
    description:
      "Abby is a graceful and affectionate 'velcro' dog who loves to be close to her people. She is both an excellent cuddler and a great runner.",
    date_created: '2023-07-07T14:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Abby',
  },
  {
    id: 55,
    name: 'Bandit',
    pet_type: 'Dog',
    age: 2.5,
    breed: 'Australian Cattle Dog',
    sex: 'Male',
    coloration: 'Blue Heeler',
    weight: 45,
    is_sterilized: true,
    description:
      'Bandit is a tough and tireless working dog. He is incredibly loyal and thrives when he has a task, making him a great partner for an active owner.',
    date_created: '2024-12-12T12:12:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Bandit',
  },
  {
    id: 56,
    name: 'Ginger',
    pet_type: 'Cat',
    age: 4,
    breed: 'Domestic Medium Hair',
    sex: 'Female',
    coloration: 'Orange',
    weight: 10,
    is_sterilized: true,
    description:
      'Ginger is a spicy, sweet girl who knows what she wants. She loves a good window perch for bird watching and is a very tidy cat.',
    date_created: '2024-06-20T15:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Ginger',
  },
  {
    id: 57,
    name: 'Zeus',
    pet_type: 'Dog',
    age: 6,
    breed: 'Rottweiler',
    sex: 'Male',
    coloration: 'Black and Mahogany',
    weight: 115,
    is_sterilized: true,
    description:
      'Zeus is a powerful dog with a calm and confident demeanor. He is fiercely loyal to his family and surprisingly gentle.',
    date_created: '2024-03-25T11:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Zeus',
  },
  {
    id: 58,
    name: 'Harley',
    pet_type: 'Dog',
    age: 5,
    breed: 'Mixed Breed',
    sex: 'Male',
    coloration: 'Brindle',
    weight: 60,
    is_sterilized: true,
    description:
      "Harley is a handsome mutt with a heart of gold. He's a perfect mix of playful energy and couch-cuddling champion.",
    date_created: '2024-04-15T18:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Harley',
  },
  {
    id: 59,
    name: 'Sasha',
    pet_type: 'Cat',
    age: 9,
    breed: 'Himalayan',
    sex: 'Female',
    coloration: 'Flame Point',
    weight: 11,
    is_sterilized: true,
    description:
      'Sasha is a beautiful and serene cat with stunning blue eyes. She enjoys a peaceful home where she can be admired.',
    date_created: '2023-08-20T10:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Sasha',
  },
  {
    id: 60,
    name: 'George',
    pet_type: 'Cat',
    age: 5,
    breed: 'Exotic Shorthair',
    sex: 'Male',
    coloration: 'Cream Tabby',
    weight: 14,
    is_sterilized: true,
    description:
      "With his squishy face, George is irresistibly cute. He's the shorthaired version of a Persian—placid, affectionate, and sweet.",
    date_created: '2024-02-22T22:22:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=George',
  },
  {
    id: 61,
    name: 'Annie',
    pet_type: 'Dog',
    age: 1.5,
    breed: 'Wheaten Terrier',
    sex: 'Female',
    coloration: 'Wheaten',
    weight: 35,
    is_sterilized: true,
    description:
      'Annie is a cheerful and friendly terrier with a silky, non-shedding coat. She greets everyone with a happy bounce.',
    date_created: '2025-01-15T15:15:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Annie',
  },
  {
    id: 62,
    name: 'Murphy',
    pet_type: 'Dog',
    age: 4,
    breed: 'Airedale Terrier',
    sex: 'Male',
    coloration: 'Black and Tan',
    weight: 65,
    is_sterilized: true,
    description:
      "Murphy is the 'King of Terriers,' a clever and adventurous dog. He's always up for a challenge and loves to play.",
    date_created: '2024-07-01T14:45:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Murphy',
  },
  {
    id: 63,
    name: 'Izzy',
    pet_type: 'Cat',
    age: 3,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Tuxedo',
    weight: 9,
    is_sterilized: true,
    description:
      'Izzy is a playful and inquisitive girl who is always dressed for a party. She loves interactive toys and exploring cardboard boxes.',
    date_created: '2024-10-01T17:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Izzy',
  },
  {
    id: 64,
    name: 'Sammy',
    pet_type: 'Cat',
    age: 12,
    breed: 'Domestic Shorthair',
    sex: 'Male',
    coloration: 'Black',
    weight: 14,
    is_sterilized: true,
    description:
      'Sammy is a sweet old man who is looking for a warm lap for his golden years. He is a champion purrer and a loving companion.',
    date_created: '2023-01-15T12:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Sammy',
  },
  {
    id: 65,
    name: 'Honey',
    pet_type: 'Dog',
    age: 6,
    breed: 'Yellow Labrador',
    sex: 'Female',
    coloration: 'Yellow',
    weight: 70,
    is_sterilized: true,
    description:
      "Honey is as sweet as her name suggests. A classic lab, she's friendly, outgoing, and loves everyone she meets.",
    date_created: '2023-12-25T11:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Honey',
  },
  {
    id: 66,
    name: 'Blue',
    pet_type: 'Dog',
    age: 3,
    breed: 'Weimaraner',
    sex: 'Male',
    coloration: 'Gray',
    weight: 75,
    is_sterilized: true,
    description:
      "Blue is a stunning 'gray ghost' with boundless energy. He needs an active family that will take him on runs and adventures.",
    date_created: '2024-08-25T09:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Blue',
  },
  {
    id: 67,
    name: 'Poppy',
    pet_type: 'Cat',
    age: 2,
    breed: 'Birman',
    sex: 'Female',
    coloration: 'Seal Point',
    weight: 10,
    is_sterilized: true,
    description:
      "Poppy is a beautiful cat known for her striking blue eyes and white 'gloves'. She has a sweet, quiet nature.",
    date_created: '2024-11-30T13:45:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Poppy',
  },
  {
    id: 68,
    name: 'Dexter',
    pet_type: 'Dog',
    age: 5,
    breed: 'Jack Russell Terrier',
    sex: 'Male',
    coloration: 'White and Tan',
    weight: 15,
    is_sterilized: true,
    description:
      "Dexter is a small dog with a big, energetic personality. He's smart, fearless, and loves to play fetch for hours.",
    date_created: '2024-05-30T16:10:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Dexter',
  },
  {
    id: 69,
    name: 'Coco',
    pet_type: 'Cat',
    age: 4,
    breed: 'Tonkinese',
    sex: 'Female',
    coloration: 'Natural Mink',
    weight: 8,
    is_sterilized: true,
    description:
      "Coco is a playful and social cat who combines the best traits of Siamese and Burmese. She's intelligent, curious, and very people-oriented.",
    date_created: '2024-07-18T10:50:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Coco',
  },
  {
    id: 70,
    name: 'Benny',
    pet_type: 'Dog',
    age: 3,
    breed: 'Corgi',
    sex: 'Male',
    coloration: 'Red and White',
    weight: 30,
    is_sterilized: true,
    description:
      "Benny is a long dog with short legs and a huge personality. He's clever, outgoing, and surprisingly athletic.",
    date_created: '2024-09-09T09:09:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Benny',
  },
  {
    id: 71,
    name: 'Grace',
    pet_type: 'Dog',
    age: 9,
    breed: 'Greyhound',
    sex: 'Female',
    coloration: 'Brindle',
    weight: 60,
    is_sterilized: true,
    description:
      "Grace is a retired racer who is now a professional couch potato. She's a gentle, quiet, and loving companion.",
    date_created: '2023-05-10T14:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Grace',
  },
  {
    id: 72,
    name: 'Midnight',
    pet_type: 'Cat',
    age: 5,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Solid Black',
    weight: 11,
    is_sterilized: true,
    description:
      "Midnight is a gorgeous house panther with sleek fur and bright yellow eyes. She's independent but enjoys affection.",
    date_created: '2024-03-13T23:59:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Midnight',
  },
  {
    id: 73,
    name: 'Otis',
    pet_type: 'Dog',
    age: 6,
    breed: 'Pug',
    sex: 'Male',
    coloration: 'Fawn',
    weight: 20,
    is_sterilized: true,
    description:
      "Otis is a charming and comical companion who lives to love and be loved. His motto is 'eat, sleep, snuggle, repeat.'",
    date_created: '2024-01-20T12:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Otis',
  },
  {
    id: 74,
    name: 'Lola',
    pet_type: 'Dog',
    age: 2,
    breed: 'Maltese',
    sex: 'Female',
    coloration: 'White',
    weight: 8,
    is_sterilized: true,
    description:
      "Lola may be small, but she's got a big, playful spirit. She's a glamor-puss who also loves to play and run around.",
    date_created: '2025-02-10T13:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Lola',
  },
  {
    id: 75,
    name: 'Walter',
    pet_type: 'Cat',
    age: 7,
    breed: 'Tabby',
    sex: 'Male',
    coloration: 'Gray and White',
    weight: 15,
    is_sterilized: true,
    description:
      "Walter is a big, friendly lug of a cat. He's a lap-cat in training and gives excellent head-butts.",
    date_created: '2023-09-25T11:25:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Walter',
  },
  {
    id: 76,
    name: 'Henry',
    pet_type: 'Dog',
    age: 8,
    breed: 'Standard Poodle',
    sex: 'Male',
    coloration: 'Apricot',
    weight: 60,
    is_sterilized: true,
    description:
      "Henry is a distinguished and intelligent older gentleman. He's calm, well-behaved, and enjoys leisurely strolls in the park.",
    date_created: '2023-02-02T10:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Henry',
  },
  {
    id: 77,
    name: 'Millie',
    pet_type: 'Cat',
    age: 1,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Dilute Calico',
    weight: 8,
    is_sterilized: false,
    description:
      "Millie is a sweet young cat with muted pastel coloring. She's a gentle soul who is just starting to come out of her shell.",
    date_created: '2025-04-20T14:10:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Millie',
  },
  {
    id: 78,
    name: 'Rudy',
    pet_type: 'Dog',
    age: 5,
    breed: 'Miniature Schnauzer',
    sex: 'Male',
    coloration: 'Salt and Pepper',
    weight: 18,
    is_sterilized: true,
    description:
      "Rudy is a spirited and alert little dog with a big bark. He's a loyal watchdog and a fun-loving companion.",
    date_created: '2024-06-06T16:06:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Rudy',
  },
  {
    id: 79,
    name: 'Stella',
    pet_type: 'Cat',
    age: 3.5,
    breed: 'Turkish Angora',
    sex: 'Female',
    coloration: 'White',
    weight: 9,
    is_sterilized: true,
    description:
      'Stella is an elegant and graceful cat with a silky long coat. She is playful, intelligent, and often forms a strong bond with one person.',
    date_created: '2024-08-18T18:18:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Stella',
  },
  {
    id: 80,
    name: 'Angus',
    pet_type: 'Dog',
    age: 4,
    breed: 'Scottish Terrier',
    sex: 'Male',
    coloration: 'Black',
    weight: 22,
    is_sterilized: true,
    description:
      "Angus is a dignified and feisty Scottie with a bold personality. He's independent but deeply loyal to his family.",
    date_created: '2024-07-25T13:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Angus',
  },
  {
    id: 81,
    name: 'Fiona',
    pet_type: 'Cat',
    age: 6,
    breed: 'Persian',
    sex: 'Female',
    coloration: 'White',
    weight: 10,
    is_sterilized: true,
    description:
      'Fiona is a quiet and sweet-tempered queen who requires regular grooming to keep her looking her best. She loves a serene household.',
    date_created: '2023-11-22T12:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Fiona',
  },
  {
    id: 82,
    name: 'Gunner',
    pet_type: 'Dog',
    age: 3,
    breed: 'Black Labrador',
    sex: 'Male',
    coloration: 'Black',
    weight: 80,
    is_sterilized: true,
    description:
      'Gunner is a strong and energetic lab who loves retrieving. He would be a perfect companion for an outdoorsy person or family.',
    date_created: '2024-09-15T10:40:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Gunner',
  },
  {
    id: 83,
    name: 'Heidi',
    pet_type: 'Dog',
    age: 5,
    breed: 'German Shepherd Mix',
    sex: 'Female',
    coloration: 'Sable',
    weight: 65,
    is_sterilized: true,
    description:
      'Heidi is a smart and loving Shepherd mix who is eager to please. She enjoys training and having a job to do.',
    date_created: '2024-04-04T14:44:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Heidi',
  },
  {
    id: 84,
    name: 'Boots',
    pet_type: 'Cat',
    age: 2,
    breed: 'Snowshoe',
    sex: 'Male',
    coloration: 'Seal Point with White',
    weight: 12,
    is_sterilized: true,
    description:
      "Boots gets his name from his four white paws. He's a clever and vocal cat who loves to be involved in whatever his people are doing.",
    date_created: '2025-01-08T17:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Boots',
  },
  {
    id: 85,
    name: 'Thor',
    pet_type: 'Dog',
    age: 2,
    breed: 'Alaskan Malamute',
    sex: 'Male',
    coloration: 'Gray and White',
    weight: 90,
    is_sterilized: true,
    description:
      'Thor is a powerful and playful dog with a thick coat built for the cold. He is friendly but needs a strong, experienced owner.',
    date_created: '2025-02-05T15:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Thor',
  },
  {
    id: 86,
    name: 'Xena',
    pet_type: 'Dog',
    age: 4,
    breed: 'Doberman Pinscher',
    sex: 'Female',
    coloration: 'Black and Rust',
    weight: 70,
    is_sterilized: true,
    description:
      'Xena is a warrior princess - elegant, intelligent, and fiercely loyal. She is a wonderful and protective family companion.',
    date_created: '2024-07-30T13:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Xena',
  },
  {
    id: 87,
    name: 'Yoshi',
    pet_type: 'Cat',
    age: 1,
    breed: 'Japanese Bobtail',
    sex: 'Male',
    coloration: 'Black, Red, and White (Mika)',
    weight: 8,
    is_sterilized: false,
    description:
      'Yoshi is a playful and clever cat with a unique pom-pom tail. He is known for being social, and enjoys playing games.',
    date_created: '2025-04-25T11:55:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Yoshi',
  },
  {
    id: 88,
    name: 'Zara',
    pet_type: 'Cat',
    age: 3,
    breed: 'Abyssinian',
    sex: 'Female',
    coloration: 'Ruddy',
    weight: 9,
    is_sterilized: true,
    description:
      'Zara is an active, curious, and athletic cat who loves to climb and explore. She thrives in a stimulating environment.',
    date_created: '2024-10-20T12:20:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Zara',
  },
  {
    id: 89,
    name: 'Ace',
    pet_type: 'Dog',
    age: 2,
    breed: 'Pointer',
    sex: 'Male',
    coloration: 'White & Liver',
    weight: 55,
    is_sterilized: true,
    description:
      "Ace is a noble and athletic dog who is always ready for an adventure. He's a fantastic companion for an active individual or family.",
    date_created: '2024-11-01T10:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Ace',
  },
  {
    id: 90,
    name: 'Bubbles',
    pet_type: 'Cat',
    age: 0.4,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Dilute Tortoiseshell',
    weight: 4,
    is_sterilized: false,
    description:
      "Bubbles is a tiny kitten with a bubbly personality. She's full of spunk and loves to chase anything that moves.",
    date_created: '2025-06-01T09:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Bubbles',
  },
  {
    id: 91,
    name: 'Cinnamon',
    pet_type: 'Cat',
    age: 3,
    breed: 'Oriental Shorthair',
    sex: 'Female',
    coloration: 'Cinnamon',
    weight: 8,
    is_sterilized: true,
    description:
      "Cinnamon is a sleek and elegant cat with large ears and a curious nature. She's very social and loves being part of the family.",
    date_created: '2024-09-20T14:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Cinnamon',
  },
  {
    id: 92,
    name: 'Diesel',
    pet_type: 'Dog',
    age: 5,
    breed: 'Cane Corso',
    sex: 'Male',
    coloration: 'Black',
    weight: 120,
    is_sterilized: true,
    description:
      'Diesel is a majestic and confident dog who is a loyal protector of his home. He needs an experienced owner.',
    date_created: '2024-05-10T11:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Diesel',
  },
  {
    id: 93,
    name: 'Echo',
    pet_type: 'Dog',
    age: 1,
    breed: 'Dalmatian',
    sex: 'Male',
    coloration: 'White & Black',
    weight: 50,
    is_sterilized: false,
    description:
      "Echo is a high-energy and playful Dalmatian. He's a real head-turner and would love a home where he can run and play.",
    date_created: '2025-03-10T12:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Echo',
  },
  {
    id: 94,
    name: 'Fern',
    pet_type: 'Cat',
    age: 7,
    breed: 'Norwegian Forest Cat',
    sex: 'Female',
    coloration: 'Brown Tabby and White',
    weight: 13,
    is_sterilized: true,
    description:
      "Fern has a luxurious coat and a love for climbing. She's a gentle giant who enjoys a good view from a high cat tree.",
    date_created: '2023-10-15T16:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Fern',
  },
  {
    id: 95,
    name: 'Gizmo',
    pet_type: 'Dog',
    age: 6,
    breed: 'Brussels Griffon',
    sex: 'Male',
    coloration: 'Red',
    weight: 10,
    is_sterilized: true,
    description:
      "Gizmo is a small dog with a big, expressive face. He's full of personality and forms a very strong bond with his favorite person.",
    date_created: '2024-02-15T17:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Gizmo',
  },
  {
    id: 96,
    name: 'Hobbes',
    pet_type: 'Cat',
    age: 5,
    breed: 'Orange Tabby',
    sex: 'Male',
    coloration: 'Orange',
    weight: 15,
    is_sterilized: true,
    description:
      "Hobbes is a large, lovable orange cat who loves pouncing and going on adventures. He's looking for his Calvin.",
    date_created: '2024-06-25T10:20:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Hobbes',
  },
  {
    id: 97,
    name: 'Juno',
    pet_type: 'Dog',
    age: 4,
    breed: 'Shiba Inu',
    sex: 'Female',
    coloration: 'Red',
    weight: 20,
    is_sterilized: true,
    description:
      'Juno is a clever and spirited Shiba with a cat-like personality. She is clean, quiet, and very smart.',
    date_created: '2024-08-10T15:45:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Juno',
  },
  {
    id: 98,
    name: 'Kiwi',
    pet_type: 'Cat',
    age: 1.5,
    breed: 'Domestic Shorthair',
    sex: 'Female',
    coloration: 'Gray',
    weight: 9,
    is_sterilized: true,
    description:
      'Kiwi is a sweet and slightly shy young cat. She loves soft blankets and would do best in a calm, patient home.',
    date_created: '2025-02-28T11:30:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Kiwi',
  },
  {
    id: 99,
    name: 'Mocha',
    pet_type: 'Dog',
    age: 3,
    breed: 'Chocolate Labrador',
    sex: 'Female',
    coloration: 'Chocolate',
    weight: 68,
    is_sterilized: true,
    description:
      "Mocha is a sweet and energetic lab who loves people, swimming, and playing fetch. She's a perfect family companion.",
    date_created: '2024-10-28T16:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Mocha',
  },
  {
    id: 100,
    name: 'Zephyr',
    pet_type: 'Cat',
    age: 2,
    breed: 'Siberian',
    sex: 'Male',
    coloration: 'Silver Tabby',
    weight: 16,
    is_sterilized: true,
    description:
      'Zephyr is a magnificent, semi-longhaired cat known for being playful and affectionate. He has a triple-layered, hypoallergenic coat.',
    date_created: '2025-01-22T14:00:00.000Z',
    picture: 'https://placehold.co/600x400/EEE/31343C?text=Zephyr',
  },
]);

export const getPetDataAsync = () => {
  return new Promise(res => {
    setTimeout(() => res(getPetDataTemp()), 1000);
  });
};

export const getFilters = () => {
  return new Promise(res => {
    setTimeout(() => {
      const data = getPetDataTemp();
      const filter = {
        type: Array.from(new Set(data.map(itm => itm.pet_type))),
        minAge: Math.min(...data.map(itm => itm.age)),
        maxAge: Math.max(...data.map(itm => itm.age)),
        breed: Array.from(new Set(data.map(itm => itm.breed))),
        sex: Array.from(new Set(data.map(itm => itm.sex))),
        coloration: Array.from(new Set(data.map(itm => itm.coloration))),
        weightMin: Math.min(...data.map(itm => itm.weight)),
        weightMax: Math.max(...data.map(itm => itm.weight)),
        isSterilized: ['Yes', 'No'],
      };

      res(filter);
    }, 1000);
  });
};

export const getPetDataTemp = (): Pet[] => {
  // return api.get(`/api/v1/pets`);

  return JSON.parse(tempData).map((itm: Pet) => {
    return { ...itm, date_created: new Date(itm.date_created) };
  });
};

export const getHomePageDogData = () => {
  return getPetDataTemp()
    .filter(pet => pet.pet_type === 'Dog')
    .slice(0, 10);
};

export const getHomePageCatData = () => {
  return getPetDataTemp()
    .filter(pet => pet.pet_type === 'Cat')
    .slice(0, 10);
};
