# Generated by Django 5.2.3 on 2025-07-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionform',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_forms', to='pet.pet'),
        ),
    ]
