name: Backend CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: .../backend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Show pwd
      run: |
        echo "Working directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        ls -la
        ls -la  backend

    - name: Load .env file
      run: |
        cp backend/.env.sample backend/.env
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Show env and pwd
      run: |
        echo "Working directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        ls -la
        ls -la backend
        

    - name: Run Tests
      run: |

        export DJANGO_SETTINGS_MODULE=config.settings.test_settings
        poetry run python manage.py test
      working-directory: backend
