name: Backend CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clean Python bytecode
      run: find . -name "__pycache__" -exec rm -rf {} +



    - name: Show pwd
      run: |
        echo "Working directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        ls -la
        ls -la  backend

    - name: Load .env file
      run: |
        cp backend/.env.sample backend/.env
    - name: Install Dependencies
      run: |
        cd backend/
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Make and run migrations
      run: |
        cd backend/
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate

    - name: Show env and pwd
      run: |
        echo "Working directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        ls -la
        ls -la backend
        

    - name: Run Tests
      run: |
        cd backend/
        poetry run python manage.py test

