# Generated by Django 5.2.3 on 2025-06-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("breed", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=10
                    ),
                ),
                ("coloration", models.CharField(blank=True, max_length=50, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                (
                    "is_sterilized",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
