# Generated by Django 5.2.3 on 2025-06-14 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={"verbose_name_plural": "pet"},
        ),
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
