# Generated by Django 5.2.3 on 2025-06-14 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_alter_pet_options_alter_pet_age_alter_pet_weight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={"verbose_name_plural": "pets"},
        ),
        migrations.AddField(
            model_name="pet",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="pet",
            constraint=models.UniqueConstraint(
                fields=("name", "type", "date_created"), name="unique_pet_per_day"
            ),
        ),
    ]
