# Generated by Django 5.2.3 on 2025-06-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0003_alter_pet_options_pet_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pet",
            name="unique_pet_per_day",
        ),
        migrations.AlterUniqueTogether(
            name="pet",
            unique_together={("name", "type", "date_created")},
        ),
    ]
