# Generated by Django 5.2.3 on 2025-06-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0004_remove_pet_unique_pet_per_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="type",
            new_name="pet_type",
        ),
        migrations.AlterUniqueTogether(
            name="pet",
            unique_together=set(),
        ),
    ]
