# Generated by Django 5.2.3 on 2025-06-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0006_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
